version: '3'
services:
  web:
    image: t8032_rayjv1
    build: .
    ports:
      - "8032:8032"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/T8032_RAYJ/volumes
